<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DC5CG138867R" failures="4" tests="16" name="Command line test" time="15.722" errors="0" timestamp="2022-05-10T13:30:43 NZST">
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.CreateUserTest" name="CreateUserId_Body" time="3.926"/>
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.CreateUserTest" name="CreateUserId_StatusCode" time="0.846"/>
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.DeleteUserTest" name="DeleteUserId_StatusCode" time="0.744"/>
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.UpdatePatchUserTest" name="patchMethodByJson" time="0.74"/>
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.UpdateUserTest" name="putMethodByJson_Body" time="0.716"/>
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.UpdateUserTest" name="putMethodByJson_StatusCode" time="0.699"/>
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.UserLoginTest" name="userLogin" time="0.724"/>
  <testcase classname="com.nahidmahmud.javaapiautomation101.reqresin.UserRegisterTest" name="userRegistration" time="0.714"/>
  <testcase classname="dummy.restapiexample.com.CopyOfGetAllEmployeeDataTest" name="allEmployeeData" time="1.024"/>
  <testcase classname="dummy.restapiexample.com.CreateEmployeeIDTest" name="CreateNewEmployee_Body" time="0.836"/>
  <testcase classname="dummy.restapiexample.com.CreateEmployeeIDTest" name="CreateNewEmployer_StatusCode" time="0.73">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;200&amp;gt; but was:&amp;lt;429&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<429>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:201)
at junit.framework.Assert.assertEquals(Assert.java:207)
at dummy.restapiexample.com.CreateEmployeeIDTest.CreateNewEmployer_StatusCode(CreateEmployeeIDTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- CreateNewEmployer_StatusCode -->
  <testcase classname="dummy.restapiexample.com.DeleteEmployeeDataTest" name="DeleteEmployer_StatusCode" time="0.759"/>
  <testcase classname="dummy.restapiexample.com.GetAllEmployeeDataTest" name="GetAllEmployeeData_Body" time="0.782">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at dummy.restapiexample.com.GetAllEmployeeDataTest.GetAllEmployeeData_Body(GetAllEmployeeDataTest.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 38 more
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- GetAllEmployeeData_Body -->
  <testcase classname="dummy.restapiexample.com.GetAllEmployeeDataTest" name="GetAllEmployeeData_StatusCode" time="0.883"/>
  <testcase classname="dummy.restapiexample.com.UpdateEmployeeIDTest" name="UpdateAnEmployeeData_Body" time="0.751">
    <failure type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at dummy.restapiexample.com.UpdateEmployeeIDTest.UpdateAnEmployeeData_Body(UpdateEmployeeIDTest.java:31)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 38 more
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UpdateAnEmployeeData_Body -->
  <testcase classname="dummy.restapiexample.com.UpdateEmployeeIDTest" name="UpdateAnEmployeeData_StatusCode" time="0.752">
    <failure type="junit.framework.AssertionFailedError" message="expected:&amp;lt;200&amp;gt; but was:&amp;lt;429&amp;gt;">
      <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<429>
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.failNotEquals(Assert.java:282)
at junit.framework.Assert.assertEquals(Assert.java:64)
at junit.framework.Assert.assertEquals(Assert.java:201)
at junit.framework.Assert.assertEquals(Assert.java:207)
at dummy.restapiexample.com.UpdateEmployeeIDTest.UpdateAnEmployeeData_StatusCode(UpdateEmployeeIDTest.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- UpdateAnEmployeeData_StatusCode -->
</testsuite> <!-- Command line test -->
